{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "domain-server.labels" . | nindent 4 }}
type: Opaque
data:
  wallet-private.key: {{ .Values.secretFile.privateKey | b64enc | quote }}
  postgres_url: {{ .Values.secretFile.postgresUrl | b64enc | quote }}
  registration_credentials: {{ .Values.secretFile.registrationCredentials | b64enc | quote }}
{{- end }}
