replicaCount: 3
containerResources:
  limits:
    cpu: 5
    memory: 5Gi
  requests:
    cpu: 1
    memory: 1Gi
envVars:
  DS_POSTGRES_POOL_SIZE: "40" # Adjusted for Azure 8vCPU database
  DS_ENABLE_EVENTS_UPLOADING: "false" # Disable events uploading for performance
  DS_DEFAULT_REQUEST_TIMEOUT: "600s" # 10 minutes
  DS_STREAM_REQUEST_TIMEOUT: "600s" # 10 minutes
  DS_LOG_LEVEL: "info"
  # configre the rest of the env vars as needed
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - domain-server-s3
        topologyKey: kubernetes.io/hostname

# You must create manually the secret with the same name as the release name used.
# - wallet-private.key
# - postgres_url
# - registration_credentials
useExistingSecret: true
postgresql:
 enabled: false

juicefs-s3-gateway:
  enabled: true
  resources:
    limits:
      cpu: 5
      memory: 5Gi
    requests:
      cpu: 1
      memory: 1Gi
  replicaCount: 3
  image:
    tag: "ce-v1.2.4" # https://github.com/juicedata/juicefs/releases
  envs:
    - name: AZURE_STORAGE_CONNECTION_STRING
      value: "GET_FROM_AZURE"
  secret:
    enabled: true
    name: "domainserver"
    metaurl: "rediss://:<redis_password>=@<redis_name>.redis.cache.windows.net:6380/0"
    storage: "wasb"
    accessKey: "GET_FROM_AZURE"
    secretKey: "GET_FROM_AZURE"
    bucket: "https://<abs_name>.core.windows.net"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - juicefs-s3-gateway
          topologyKey: kubernetes.io/hostname

