{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "compute-node.uiDeploymentName" . }}
  labels:
    {{- include "compute-node.nodeLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "compute-node.nodeSelectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "compute-node.nodeSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "compute-node.serviceAccountName" . }}
      {{- end }}
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.ui.port | default 3000 }}
          protocol: TCP
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.port | default 3000 }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.ui.port | default 3000 }}
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
