# Default values for compute-node
# This is a YAML-formatted file.

# Service Account configuration
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Server configuration
server:
  enabled: true
  replicas: 1
  image:
    # repository: ""
    tag: "latest"
    pullPolicy: Always
  resources: {}
  ports:
    main: 8080
    admin: 18190
  tolerations: {}
  # Extra keys added to the configmap that are then supplied as env vars to the server
  extraConfig: {}
  # Extra env vars
  env: {}
  enableProbes: true

# UI configuration
ui:
  enabled: true
  replicas: 1
  port: 3000
  image:
    # repository: ""
    tag: "latest"
    pullPolicy: Always
  resources: {}
  enableProbes: true

# Database configuration
postgresql:
  # If true, the PostgreSQL dependency is enabled
  enabled: false
  url: "placeholder"
  global:
    # defaultStorageClass: ""
    postgresql:
      auth:
        # The defaults are the name of the Helm deployment
        # username: deployment-name
        # password: deployment-name
        # database: deployment-name
  primary:
    networkPolicy:
      enabled: false
    resources: {}

# Storage configuration
storage:
  enabled: true
  # storageClass: ""
  size: "100Gi"
  accessMode: ReadWriteOnce
  mountPath: /data

# Ingress configuration
ingress:
  enabled: false
  # className: nginx
  annotations:
    # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - chart-example.local
  # tls:
  #   - secretName: chart-example-tls
  #     hosts:
  #       - chart-example.local

# Service configuration
service:
  type: ClusterIP
  annotations: {}

# Security configuration
security:
  createSecret: true
  appKey: "changeme"
  appSecret: "changeme"
  # Or use an existing secret:
  # existingSecretName: ""

# Labels and annotations
labels: {}
annotations: {}
