name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # https://github.com/kubernetes-sigs/kind/releases
        kind_version: [v0.14.0]
        k8s_version: [v1.24.0, v1.23.6, v1.22.9, v1.21.12, v1.20.15, v1.19.16, v1.18.20]
        include:
          - kind_version: v0.12.0
            k8s_version: v1.14.10
          - kind_version: v0.12.0
            k8s_version: v1.17.17
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          version: ${{ matrix.kind_version }}
          node_image: kindest/node:${{ matrix.k8s_version }}
          kubectl_version: ${{ matrix.k8s_version }}

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
