{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hagall.fullname" . }}
  labels:
    {{- include "hagall.labels" . | nindent 4 }}
type: Opaque
data:
  hagall-private.key: {{ .Values.secrets.privateKey | b64enc | quote }}
{{- end }}
